USE DB_E_COMERCE

SELECT * FROM TB_USUARIO
SELECT * FROM TB_PRODUTO
SELECT * FROM TB_COMPRAS

INSERT INTO TB_USUARIO
VALUES 
('Jean','jof@gmail.com','102938','12345678900'),
('Jão','kkk@gmail.com','654783','09876543211');


INSERT INTO TB_PRODUTO
VALUES 
('Air Fryer','Ótimas condições',110,1,'ELETRODOMÉSTICO','IMAGEM'),
('Descascador','Produto importado',125,15,'UTENSÍLIOS','IMAGEM');


INSERT INTO TB_COMPRAS
VALUES 
(1,2,'05/05/2022');

SELECT * FROM TB_USUARIO WHERE NOME = 'JÃO'	

SELECT u.ID, z.ID
FROM TB_USUARIO AS u
LEFT JOIN TB_PRODUTO z
ON u.ID = z.ID

SELECT COUNT (estoque)
FROM TB_PRODUTO;

SELECT * FROM TB_USUARIO
WHERE NOME LIKE '%N%';