CREATE DATABASE DB_E_COMERCE
	USE DB_E_COMERCE

CREATE TABLE TB_USUARIO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(45) NOT NULL,
	USUARIO VARCHAR(45) NOT NULL, 
	SENHA VARCHAR(100) NOT NULL,
	CPF VARCHAR(15) NOT NULL,
);

CREATE TABLE TB_PRODUTO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	PRODUTO VARCHAR(45) NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	VALOR FLOAT	NOT NULL,
	ESTOQUE INT NOT NULL,
	CATEGORIA VARCHAR (50) NOT NULL,
	URL_IMAGEM VARCHAR(100) NOT NULL,
	
);

CREATE TABLE TB_COMPRAS(
	FK_USUARIO INT NOT NULL,
	FK_PRODUTO INT NOT NULL,
	DIA_MES_ANO DATE NOT NULL,
	FOREIGN KEY (FK_USUARIO) REFERENCES TB_USUARIO(ID),
	FOREIGN KEY (FK_PRODUTO) REFERENCES TB_PRODUTO(ID),
);
