CREATE DATABASE DB_CLASSIFICADO
USE DB_CLASSIFICADO

CREATE TABLE TB_USUARIO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(45) NOT NULL,
	USUARIO VARCHAR(45) NOT NULL, 
	SENHA VARCHAR(100) NOT NULL,
	TIPO VARCHAR (50)NOT NULL,
	URL_IMAGEM VARCHAR(100) NOT NULL,
);

CREATE TABLE TB_ANUNCIOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	TITULO VARCHAR(45) NOT NULL,
	DESCRICAO VARCHAR(1000) NOT NULL,
	CONTATO VARCHAR(50) NOT NULL,
	URL_IMAGEM VARCHAR(100) NOT NULL,
	DIA_MES_ANO DATE NOT NULL,
	FK_USUARIO INT NOT NULL,
	FOREIGN KEY (FK_USUARIO) REFERENCES TB_USUARIO(ID),
);
